everTrucking-Web/Controllers/DanhMucController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using PagedList;
using cenDTO.cenLogistics;
using cenBUS.cenLogistics;
using cenBUS.DatabaseCore;
using cenDTO.DatabaseCore;
using cenDTO;

namespace everTrucking_Web.Controllers
{
    public class DanhMucController : Controller
    {
        //KHÁCH HÀNG
        public ActionResult KhachHangIndex()
        {
            UserSession Session = UserSessionHelper.GetSession();
            if (Session == null)
                return RedirectToAction("Login", "DanhMucNguoiSuDung");
            return View();
        }
        public JsonResult ListKhachHang()
        {
            DataTable dtDanhMucKhachHang = DanhMucKhachHangBUS.List(null, DanhMucLoaiDoiTuongBUS.GetID(DanhMucThamSoHeThongBUS.GetGiaTri(cenCommon.ThamSoHeThong.MaThamSoLoaiDoiTuongKhachHang)), null);
            List<DanhMucKhachHang> listKhachHang = new List<DanhMucKhachHang>();
            foreach (DataRow drKhachHang in dtDanhMucKhachHang.Rows)
            {
                listKhachHang.Add(new DanhMucKhachHang()
                {
                    ID = drKhachHang["ID"].ToString(),
                    IDDanhMucDonVi = drKhachHang["IDDanhMucDonVi"].ToString(),
                    IDDanhMucLoaiDoiTuong = drKhachHang["IDDanhMucLoaiDoiTuong"].ToString(),
                    Ma = drKhachHang["Ma"].ToString(),
                    Ten = drKhachHang["Ten"].ToString(),
                    MaCS = drKhachHang["MaCS"].ToString(),
                    IDDanhMucNguoiSuDungEdit = drKhachHang["IDDanhMucNguoiSuDungEdit"].ToString(),
                    IDDanhMucNguoiSuDungCreate = drKhachHang["IDDanhMucNguoiSuDungCreate"].ToString(),
                    TenEN = drKhachHang["TenEN"].ToString(),
                    DiaChi = drKhachHang["DiaChi"].ToString(),
                    MaSoThue = drKhachHang["MaSoThue"].ToString(),
                    Nhom = drKhachHang["Nhom"].ToString(),
                    ViTri = drKhachHang["ViTri"].ToString(),
                    LoaiKhachHang = drKhachHang["LoaiKhachHang"].ToString(),
                    TenLoaiKhachHang = drKhachHang["TenLoaiKhachHang"].ToString(),
                    GhiChu = drKhachHang["GhiChu"].ToString(),
                    CreateDate = drKhachHang["CreateDate"].ToString(),
                    EditDate = drKhachHang["EditDate"].ToString(),
                });

            }
            ViewBag.ListKhachHang = listKhachHang;
           
            return Json(listKhachHang, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetKhachHangbyID(string ID)
        {
            DataTable dtDanhMucKhachHang = DanhMucKhachHangBUS.List(ID, DanhMucLoaiDoiTuongBUS.GetID(DanhMucThamSoHeThongBUS.GetGiaTri(cenCommon.ThamSoHeThong.MaThamSoLoaiDoiTuongKhachHang)), null);
            DanhMucKhachHang obj = null;
            if (dtDanhMucKhachHang.Rows.Count == 1)
            {
                obj = new DanhMucKhachHang()
                {
                    ID = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["ID"]),
                    IDDanhMucDonVi = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["IDDanhMucDonVi"]),
                    IDDanhMucLoaiDoiTuong = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["IDDanhMucLoaiDoiTuong"]),
                    Ma = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["Ma"]),
                    Ten = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["Ten"]),
                    MaCS = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["MaCS"]),
                    TenEN = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["TenEN"]),
                    DiaChi = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["DiaChi"]),
                    MaSoThue = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["MaSoThue"]),
                    Nhom = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["Nhom"]),
                    ViTri = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["ViTri"]),
                    LoaiKhachHang = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["LoaiKhachHang"]),
                    TenLoaiKhachHang = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["TenLoaiKhachHang"]),
                    GhiChu = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["GhiChu"]),
                    IDDanhMucNguoiSuDungCreate = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["IDDanhMucNguoiSuDungCreate"]),
                    IDDanhMucNguoiSuDungEdit = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["IDDanhMucNguoiSuDungEdit"]),
                    CreateDate = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["CreateDate"]),
                    EditDate = cenCommon.cenCommon.stringParse(dtDanhMucKhachHang.Rows[0]["EditDate"]),
                };
            }
            
            var Employee = obj;
            return Json(Employee, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpdateKhachHang(DanhMucKhachHang emp)
        {
            emp.IDDanhMucNguoiSuDungEdit = UserSessionHelper.GetSession().IDDanhMucNguoiSuDung;
            cenDTO.msgResponse msgResponse =  DanhMucKhachHangBUS.Update(ref emp);
            return Json(msgResponse, JsonRequestBehavior.AllowGet);
        }
        public JsonResult AddKhachHang(DanhMucKhachHang emp)          
        {
            emp.IDDanhMucDonVi = cenCommon.GlobalVariables.IDDonVi;
            emp.IDDanhMucLoaiDoiTuong = DanhMucLoaiDoiTuongBUS.GetID(DanhMucThamSoHeThongBUS.GetGiaTri(cenCommon.ThamSoHeThong.MaThamSoLoaiDoiTuongKhachHang));
            emp.IDDanhMucNguoiSuDungCreate = UserSessionHelper.GetSession().IDDanhMucNguoiSuDung;
            cenDTO.msgResponse msgResponse = DanhMucKhachHangBUS.Insert(ref emp);
            msgResponse.Data = Newtonsoft.Json.JsonConvert.SerializeObject(emp);
            return Json(msgResponse, JsonRequestBehavior.AllowGet);
        }
        public JsonResult DeleteKhachHang(string ID)
        {
            cenDTO.msgResponse msgResponse =  DanhMucKhachHangBUS.Delete(ID);
            return Json(msgResponse, JsonRequestBehavior.AllowGet);
        }
        //SALE
        public ActionResult SaleIndex()
        {
            UserSession Session = UserSessionHelper.GetSession();
            if (Session == null)
                return RedirectToAction("Login", "DanhMucNguoiSuDung");
            return View();
        }
        public JsonResult ListSale()
        {
            DataTable dtDanhMucSale = DanhMucDoiTuongBUS.List(null, DanhMucLoaiDoiTuongBUS.GetID(DanhMucThamSoHeThongBUS.GetGiaTri(cenCommon.ThamSoHeThong.MaThamSoLoaiDoiTuongNhanSu)), null);
            List<DanhMucDoiTuong> listSale = new List<DanhMucDoiTuong>();
            foreach (DataRow drSale in dtDanhMucSale.Rows)
            {
                listSale.Add(new DanhMucDoiTuong()
                {
                    ID = drSale["ID"].ToString(),
                    IDDanhMucDonVi = drSale["IDDanhMucDonVi"].ToString(),
                    IDDanhMucLoaiDoiTuong = drSale["IDDanhMucLoaiDoiTuong"].ToString(),
                    Ma = drSale["Ma"].ToString(),
                    Ten = drSale["Ten"].ToString(),
                    IDDanhMucNguoiSuDungEdit = drSale["IDDanhMucNguoiSuDungEdit"].ToString(),
                    IDDanhMucNguoiSuDungCreate = drSale["IDDanhMucNguoiSuDungCreate"].ToString(),
                    CreateDate = drSale["CreateDate"].ToString(),
                    EditDate = drSale["EditDate"].ToString(),
                });

            }
            ViewBag.ListSale = listSale;

            return Json(listSale, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetSalebyID(string ID)
        {
            DataTable dtDanhMucSale = DanhMucDoiTuongBUS.List(ID, DanhMucLoaiDoiTuongBUS.GetID(DanhMucThamSoHeThongBUS.GetGiaTri(cenCommon.ThamSoHeThong.MaThamSoLoaiDoiTuongNhanSu)), null);
            DanhMucDoiTuong obj = null;
            if (dtDanhMucSale.Rows.Count == 1)
            {
                obj = new DanhMucDoiTuong()
                {
                    ID = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["ID"]),
                    IDDanhMucDonVi = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["IDDanhMucDonVi"]),
                    IDDanhMucLoaiDoiTuong = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["IDDanhMucLoaiDoiTuong"]),
                    Ma = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["Ma"]),
                    Ten = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["Ten"]),
                    IDDanhMucNguoiSuDungCreate = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["IDDanhMucNguoiSuDungCreate"]),
                    IDDanhMucNguoiSuDungEdit = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["IDDanhMucNguoiSuDungEdit"]),
                    CreateDate = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["CreateDate"]),
                    EditDate = cenCommon.cenCommon.stringParse(dtDanhMucSale.Rows[0]["EditDate"]),
                };
            }

            var Employee = obj;
            return Json(Employee, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpdateSale(DanhMucDoiTuong emp)
        {
            emp.IDDanhMucNguoiSuDungEdit = UserSessionHelper.GetSession().IDDanhMucNguoiSuDung;
            cenDTO.msgResponse msgResponse = DanhMucDoiTuongBUS.Update(ref emp);
            return Json(msgResponse, JsonRequestBehavior.AllowGet);
        }
        public JsonResult AddSale(DanhMucDoiTuong emp)
        {
            emp.IDDanhMucDonVi = cenCommon.GlobalVariables.IDDonVi;

everTrucking-Web/Views/DanhMuc/CangICDIndex.cshtml
@model List<cenDTO.cenLogistics.DanhMucDiaDiemGiaoNhan>


@{
    ViewBag.Title = "Danh mục cảng, icd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table-bordered tr th {
        font-size: 14px;
        font-weight: 600 !important;
    }

    .title {
        align-items: center
    }
</style>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div>
            <h6 class="m-0 font-weight-bold text-primary">
                DANH MỤC CẢNG, ICD
            </h6>
        </div>
    </div>
    <div class="card-header py-3 ">
        <div class="title d-flex justify-content-between mb-3">
            <div>
                <button type="button" onclick="clearTextBox()" class="btn btn-primary" data-toggle="modal" data-target="#frmCangICDUpdate"> <i class="fa fa-plus"></i> Thêm mới</button>
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered" id="tblDanhMucCangICD">
        <thead>
            <tr>
                <th style="width:15%;">Mã cảng</th>
                <th>Tên cảng</th>
                <th>Địa chỉ</th>
                <th style="width:10%;">Thao tác</th>
            </tr>
        </thead>
        <tbody class="tbody1">
        </tbody>
    </table>

</div>


<div class="modal fade" id="frmCangICDUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Thêm cảng mới</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row" id="dvPartial">

                    <div class="col-12">
                        <div class="form-group">
                            <input id="ID" type="hidden" name="ID" />
                            <input id="IDDanhMucDonVi" type="hidden" name="IDDanhMucDonVi" class="form-control" />
                            <input id="IDDanhMucLoaiDoiTuong" type="hidden" name="IDDanhMucLoaiDoiTuong" class="form-control" />
                            <label>Mã :</label>
                            <input id="txtMa" type="text" name="Ma" value="" class="form-control" />
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label>Tên:</label>
                            <input id="txtTen" type="text" name="Ten" value="" class="form-control" />
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label>Địa chỉ:</label>
                            <input id="txtDiaChi" type="text" name="Ten" value="" class="form-control" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnAdd" class="btn btn-primary" onclick="Add()">Save changes</button>
                <button type="button" class="btn btn-primary" id="btnUpdate" style="display:none;" onclick="Update();">Update</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        loadData();
    });
    function loadData() {
        if ($.fn.dataTable.isDataTable('#tblDanhMucCangICD')) {
            $('#tblDanhMucCangICD').dataTable().fnDestroy();
        }
        $.ajax({
            url: "@Url.Action("ListCangICD", "DanhMuc")",
            type: "GET",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                var html = '';
                if (result.length > 0) {
                    $.each(result, function (key, item) {
                        html += '<tr id="IDCang_' + item.ID + '">';
                        html += '<td id="MaCang_' + item.ID + '">' + item.Ma + '</td>';
                        html += '<td id="TenCang_' + item.ID + '">' + item.Ten + '</td>';
                        html += '<td id="DiaChiCang_' + item.ID + '">' + item.DiaChi + '</td>';
                        html += '<td><a href="#" onclick="return getbyID(' + item.ID + ')"><i class="fa fa-pen fa-1x mr-1"></i></a> | <a href="#" onclick="Delele(' + item.ID + ')"><i class="fa fa-trash fa-1x ml-1"></i></a></td>';
                        html += '</tr>';
                    });
                }
                $('.tbody1').html(html);
                $('#tblDanhMucCangICD').DataTable({
                    "aLengthMenu": [[25, 50, 75, -1], [25, 50, 75, "All"]],
                    "iDisplayLength": 25
                });
            },
            error: function (errorMesage) {
                alert(errorMesage.responseText);
            }
        });
    }

    //Add Data Function
    function Add() {
        var empObj = {
            Ma: $('#txtMa').val(),
            Ten: $('#txtTen').val(),
            DiaChi: $('#txtDiaChi').val(),
        };
        var url = "@Url.Action("AddCangICD", "DanhMuc")"
        $.ajax({
            url: url,
            data: JSON.stringify(empObj),
            type: "POST",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {

                if (result.Status == '00') {

                    var added = JSON.parse(result.Data);

                    var html = '';
                    html += '<tr id="IDCang_' + added.ID + '">';
                    html += '<td id="MaCang_' + added.ID + '">' + added.Ma + '</td>';
                    html += '<td id="TenCang_' + added.ID + '">' + added.Ten + '</td>';
                    html += '<td id="DiaChiCang_' + added.ID + '">' + added.DiaChi + '</td>';
                    html += '<td><a href="#" onclick="return getbyID(' + added.ID + ')"><i class="fa fa-pen fa-1x mr-1"></i></a> | <a href="#" onclick="Delele(' + added.ID + ')"><i class="fa fa-trash fa-1x ml-1"></i></a></td>';
                    html += '</tr>';

                    var dataTable = $('#tblDanhMucCangICD').DataTable();
                    dataTable.row.add($(html)).draw(false);

                    clearTextBox();

                    $('#frmCangICDUpdate').modal('hide');
                }
                else {
                    alert('Lỗi thêm: ' + result.Message);
                }
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
        }

    function getbyID(EmpID) {

        $.ajax({
            url: "/DanhMuc/GetCangICDbyID/" + EmpID,
            typr: "GET",
            contentType: "application/json;charset=UTF-8",
            dataType: "json",
            success: function (result) {
                $('#ID').val(result.ID);
                $('#IDDanhMucDonVi').val(result.IDDanhMucDonVi);
                $('#IDDanhMucLoaiDoiTuong').val(result.IDDanhMucLoaiDoiTuong);
                $('#txtMa').val(result.Ma);
                $('#txtTen').val(result.Ten);
                $('#txtDiaChi').val(result.DiaChi);
                $('#IDDanhMucNguoiSuDungCreate').val(result.IDDanhMucNguoiSuDungCreate);
                $('#IDDanhMucNguoiSuDungEdit').val(result.IDDanhMucNguoiSuDungEdit);
                $('#frmCangICDUpdate').modal('show');
                $('#btnUpdate').show();
                $('#btnAdd').hide();
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
        return false;
    }

     function Update() {

        var empObj = {
            ID: $('#ID').val(),
            IDDanhMucDonVi: $('#IDDanhMucDonVi').val(),
            IDDanhMucLoaiDoiTuong: $('#IDDanhMucLoaiDoiTuong').val(),
            Ma: $('#txtMa').val(),
            Ten: $('#txtTen').val(),
            DiaChi: $('#txtDiaChi').val(),
            IDDanhMucNguoiSuDungCreate: $('#IDDanhMucNguoiSuDungCreate').val(),
            IDDanhMucNguoiSuDungEdit: $('#IDDanhMucNguoiSuDungEdit').val(),
        };
    var url = "@Url.Action("UpdateCangICD", "DanhMuc")"
        $.ajax({
        url: url,
            data: JSON.stringify(empObj),
            type: "POST",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {

                if (result.Status == '00') {

                    ID: $('#ID').val("");
                    IDDanhMucDonVi: $('#IDDanhMucDonVi').val("");
                    IDDanhMucLoaiDoiTuong: $('#IDDanhMucLoaiDoiTuong').val("");
                    Ma: $('#txtMa').val("");
                    Ten: $('#txtTen').val("");
                    DiaChi: $('#txtDiaChi').val("");
                    IDDanhMucNguoiSuDungCreate: $('#IDDanhMucNguoiSuDungCreate').val("");
                    IDDanhMucNguoiSuDungEdit: $('#IDDanhMucNguoiSuDungEdit').val("");
                    EditDate: $('#Ngaysua').val("");

                    $('#MaCang_' + empObj.ID).html(empObj.Ma);
                    $('#TenCang_' + empObj.ID).html(empObj.Ten);
                    $('#DiaChiCang_' + empObj.ID).html(empObj.Ten);

                    clearTextBox();
                    $('#frmCangICDUpdate').modal('hide');
                }
                else {
                    alert('Lỗi sửa: ' + result.Message);
                }
            },
            error: function (errormessage) {

                alert(errormessage.responseText);
            }
        });
    }

    function Delele(ID) {
    var ans = confirm("Bạn chắc chắn muốn xóa bản ghi này?");
    if (ans) {
            $.ajax({
                url: "/DanhMuc/DeleteCangICD/" + ID,
                type: "POST",
                contentType: "application/json;charset=UTF-8",
                dataType: "json",
                success: function (result) {
                    if (result.Status == '00') {
                        var dataTable = $('#tblDanhMucCangICD').DataTable();
                        dataTable.$('#IDCang_' + ID).addClass('selected');
                        dataTable.row('.selected').remove().draw(false);
                    }
                    else {
                        alert('Lỗi xóa: ' + result.Message);
                    }
                },
                error: function (errormessage) {
                    alert(errormessage.responseText);
                }
            });
        }
    }
    function clearTextBox() {
        $('#ID').val("");
        $('#IDDanhMucDonVi').val("");
        $('#IDDanhMucLoaiDoiTuong').val("");
        $('#txtMa').val("");
        $('#txtTen').val("");
        $('#txtDiaChi').val("");
        $('#btnUpdate').hide();
        $('#btnAdd').show();
        $('#IDDanhMucNguoiSuDungCreate').val("");
        $('#IDDanhMucNguoiSuDungEdit').val("");
        $('#Ngaytao').val("");
        $('#Ngaysua').val("")
    }
</script>